// Scripting code

var shoutOuts = ["Patterns downloaded from www.subtlepatterns.com If you need more, that's where to get'em.", "Go to www.unsplash.com for free high-resolution photos", "Some animations Generated by Animista on http://animista.net"];

console.log(shoutOuts[0] + "\n\n" + shoutOuts[1] + "\n\n" + shoutOuts[2]);