// Giving Credit to helpful tools and resources I've used throughout the Project.
var shoutOuts = ["Patterns downloaded from www.subtlepatterns.com If you need more, that's where to get'em.", "Go to www.unsplash.com for free high-resolution photos", "Some animations Generated by Animista on http://animista.net", " Some Animations Generated By WOW.js on https://wowjs.uk/"];
console.log(shoutOuts[0] + "\n\n" + shoutOuts[1] + "\n\n" + shoutOuts[2] + "\n\n" + shoutOuts[2]);

//----------------------------------------------------------------------------------------

//var colors = ["#7da0b5", "#7fb0b5", "#497478"]

//--------------Hamburger code for smaller resolutions--------------------------------

let nav = document.getElementsByTagName("nav");
let menuIcon = document.querySelector('#menu-icon');
let comp = window.getComputedStyle(menuIcon);


window.addEventListener("orientationchange", function() {
    // Switch the Navbar between visible and not visible 
    // if the user changes the orientation of their device after the page has already loaded
    if(window.matchMedia("(orientation: portrait)").matches && comp.getPropertyValue('display') == 'block'){
        nav[0].style.width = "100%";
    }else{
        nav[0].style.width = "0%";
    }
    
});

function openNav() {
    nav[0].style.width = "100%";
}

function closeNav() {
    if(comp.getPropertyValue('display') == 'block'){
        nav[0].style.width = "0%";
    }
}
//------------------------------------------------------------------------------


//-------------sticky NAV--------------------------
window.onscroll = function() {stickyBar()};

function stickyBar() {
    if (window.pageYOffset > document.getElementById("nav").offsetTop && window.matchMedia("(max-width: 780px)").matches == false) {
        document.getElementById("nav").classList.add("sticky");
    } else {
        document.getElementById("nav").classList.remove("sticky");
    }
  }
//-------------------------------------------------
